# Generated by Django 5.1 on 2025-02-27 01:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("tuhi", "0002_pagesection_content2"),
        ("tuhi", "0003_remove_pagesection_content"),
        ("tuhi", "0004_rename_content2_pagesection_content"),
    ]

    dependencies = [
        ("tuhi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagesection",
            name="content",
        ),
        migrations.AddField(
            model_name="pagesection",
            name="content",
            field=tinymce.models.HTMLField(default=""),
        ),
    ]
