# Generated by Django 5.1 on 2025-02-27 01:19

import tinymce.models
from django.db import migrations
from ..models import Page


def quill_to_tinymce(apps, schema_editor):
    for page in Page.objects.all():
        for section in page.sections.all():
            section.content2 = section.content.html
            section.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesection",
            name="content2",
            field=tinymce.models.HTMLField(default=""),
            preserve_default=False,
        ),
        migrations.RunPython(quill_to_tinymce, elidable=True),
    ]
