# Generated by Django 5.1 on 2025-02-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0002_pagesection_content2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagesection",
            name="content",
        ),
    ]
