# Generated by Django 5.2.dev20240719125256 on 2024-07-20 11:36

from django.db import migrations


def migrate_page_sections(apps, schema_editor):
    Page = apps.get_model("tuhi", "Page")
    PageSection = apps.get_model("tuhi", "PageSection")
    for page in Page.objects.all():
        PageSection.objects.create(
            page=page,
            content=page.contents
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0002_pagesection"),
    ]

    operations = [
        migrations.RunPython(migrate_page_sections),
    ]
