# Generated by Django 5.2.dev20240719125256 on 2024-07-20 11:36

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuhi", "0003_pagecontent_backfill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="content",
        ),
        migrations.AddField(
            model_name="page",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
