# Generated by Django 5.1 on 2025-03-07 16:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tuhi",
            "0002_pagesection_content2_squashed_0004_rename_content2_pagesection_content",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pagesection",
            name="draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
