# Generated by Django 5.1.dev20240126013232 on 2024-01-26 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="draft",
            new_name="is_draft",
        ),
    ]
