# Generated by Django 5.1.dev20240126145137 on 2024-01-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_draft_post_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="draft status"),
        ),
    ]
