# Generated by Django 5.0.3 on 2024-03-10 17:55

import apps.tara.models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextRoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=32)),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_root",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tara.contextroot",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contextroot",
            name="sites",
            field=models.ManyToManyField(through="tara.SiteContext", to="sites.site"),
        ),
        migrations.CreateModel(
            name="ContextNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[apps.tara.models.is_path],
                    ),
                ),
                ("context_id", models.PositiveIntegerField()),
                (
                    "context_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tara.contextnode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["context_type", "context_id"],
                        name="tara_contex_context_f432b0_idx",
                    ),
                    models.Index(
                        fields=["parent", "path"], name="tara_contex_parent__78e3ae_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="contextnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("parent__isnull", True), ("path__isnull", True), _negated=True
                ),
                fields=("path", "parent"),
                name="tara_contextnode_unique_context_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="contextroot",
            constraint=models.UniqueConstraint(
                fields=("name",), name="tara_contextroot_unique_name"
            ),
        ),
    ]
