# Generated by Django 5.0.3 on 2024-04-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("tara", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contextroot",
            name="created",
        ),
        migrations.RemoveField(
            model_name="contextroot",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="contextroot",
            name="id",
        ),
        migrations.RemoveField(
            model_name="contextroot",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="contextroot",
            name="modified_by",
        ),
        migrations.AddField(
            model_name="contextroot",
            name="contextnode_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="tara.contextnode",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contextnode",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tara.contextnode",
            ),
        ),
        migrations.AlterField(
            model_name="contextnode",
            name="path",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contextroot",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="sitecontext",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sites.site",
                unique=True,
            ),
        ),
    ]
