# Generated by Django 5.0.3 on 2024-04-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tara", "0002_remove_contextroot_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="contextroot",
            name="tara_contextroot_unique_name",
        ),
        migrations.RemoveIndex(
            model_name="contextnode",
            name="tara_contex_context_f432b0_idx",
        ),
        migrations.RenameField(
            model_name="contextnode",
            old_name="context_id",
            new_name="content_id",
        ),
        migrations.RenameField(
            model_name="contextnode",
            old_name="context_type",
            new_name="content_type",
        ),
        migrations.RemoveField(
            model_name="contextnode",
            name="created",
        ),
        migrations.RemoveField(
            model_name="contextnode",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="contextnode",
            name="id",
        ),
        migrations.RemoveField(
            model_name="contextnode",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="contextnode",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="contextroot",
            name="contextnode_ptr",
        ),
        migrations.AddField(
            model_name="contextnode",
            name="context_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="tara.context",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contextroot",
            name="context_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="tara.context",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="contextnode",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="tara_contex_content_1a00ea_idx",
            ),
        ),
    ]
