# Generated by Django 5.0.3 on 2024-04-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tara", "0003_context_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contextnode",
            name="tara_contextnode_unique_context_path",
        ),
        migrations.AddConstraint(
            model_name="contextnode",
            constraint=models.UniqueConstraint(
                fields=("path", "parent"), name="tara_contextnode_unique_context_path"
            ),
        ),
    ]
