# Generated by Django 5.0.3 on 2024-04-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        (
            "tara",
            "0004_remove_contextnode_tara_contextnode_unique_context_path_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontext",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
    ]
