# Generated by Django 5.0.3 on 2024-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tara", "0005_alter_sitecontext_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contextnode",
            name="path",
            field=models.SlugField(blank=True),
        ),
    ]
