# Generated by Django 5.1 on 2023-10-09 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mbme", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
