# Generated by Django 5.1.dev20240301150034 on 2024-03-03 05:03

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("url", models.URLField(max_length=128)),
                (
                    "icon",
                    models.ImageField(
                        height_field="height", upload_to="brand/", width_field="width"
                    ),
                ),
                ("height", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("width", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "creator",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
