# Generated by Django 5.1.dev20240126145137 on 2024-01-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("awa", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="security_level",
        ),
        migrations.CreateModel(
            name="AwaGroupObjectPermission",
            fields=[
                (
                    "object_pk",
                    models.CharField(max_length=255, verbose_name="object ID"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_pk"],
                        name="awa_awagrou_content_ee2efd_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_pk", "group"],
                        name="awa_awagrou_content_20caf4_idx",
                    ),
                ],
                "unique_together": {("group", "permission", "object_pk")},
            },
        ),
        migrations.CreateModel(
            name="AwaUserObjectPermission",
            fields=[
                (
                    "object_pk",
                    models.CharField(max_length=255, verbose_name="object ID"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                ("sites", models.ManyToManyField(to="sites.site")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_pk"],
                        name="awa_awauser_content_966245_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_pk", "user"],
                        name="awa_awauser_content_f7c912_idx",
                    ),
                ],
                "unique_together": {("user", "permission", "object_pk")},
            },
        ),
    ]
