# Generated by Django 5.0.3 on 2024-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awa", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brandlink",
            old_name="height",
            new_name="icon_height",
        ),
        migrations.RenameField(
            model_name="brandlink",
            old_name="width",
            new_name="icon_width",
        ),
        migrations.AlterField(
            model_name="brandlink",
            name="icon",
            field=models.ImageField(
                blank=True,
                height_field="icon_height",
                null=True,
                upload_to="icons/",
                width_field="icon_width",
            ),
        ),
    ]
