# Generated by Django 5.1 on 2023-10-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0
            ),
        ),
    ]
