# Generated by Django 5.1.dev20240129203454 on 2024-01-29 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("awa", "0002_remove_user_security_level_awagroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awauserobjectpermission",
            name="sites",
        ),
    ]
