# Generated by Django 5.1 on 2025-01-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awa", "0002_link_delete_projectlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="role",
            field=models.CharField(
                choices=[
                    ("header", "Header"),
                    ("footer", "Footer"),
                    ("random", "Random"),
                ],
                default="unset",
                max_length=10,
            ),
        ),
    ]
