# Generated by Django 5.1 on 2023-10-30 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mbme", "0002_user_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="level",
            new_name="security_level",
        ),
    ]
