# Generated by Django 5.1.dev20240201152335 on 2024-02-01 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("awa", "0003_remove_awauserobjectpermission_sites"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AwaGroupObjectPermission",
            new_name="GroupPermission",
        ),
        migrations.RenameModel(
            old_name="AwaUserObjectPermission",
            new_name="UserPermission",
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RenameIndex(
            model_name="grouppermission",
            new_name="awa_grouppe_content_1c00b9_idx",
            old_name="awa_awagrou_content_ee2efd_idx",
        ),
        migrations.RenameIndex(
            model_name="grouppermission",
            new_name="awa_grouppe_content_22d956_idx",
            old_name="awa_awagrou_content_20caf4_idx",
        ),
        migrations.RenameIndex(
            model_name="userpermission",
            new_name="awa_userper_content_f8ad8d_idx",
            old_name="awa_awauser_content_966245_idx",
        ),
        migrations.RenameIndex(
            model_name="userpermission",
            new_name="awa_userper_content_b3319c_idx",
            old_name="awa_awauser_content_f7c912_idx",
        ),
    ]
