# Generated by Django 5.1 on 2023-12-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awa", "0003_rename_level_user_security_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("url", models.URLField(max_length=128)),
                (
                    "icon",
                    models.ImageField(
                        height_field="height", upload_to="social/", width_field="width"
                    ),
                ),
                ("height", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("width", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
