# Generated by Django 5.1.dev20240201152335 on 2024-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awa", "0004_rename_awagroupobjectpermission_grouppermission_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_types",
                    models.ManyToManyField(to="contenttypes.contenttype"),
                ),
                ("groups", models.ManyToManyField(to="awa.grouppermission")),
                ("sites", models.ManyToManyField(to="sites.site")),
                ("users", models.ManyToManyField(to="awa.userpermission")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
