# Generated by Django 5.1 on 2025-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awa", "0004_sitelink_delete_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitelink",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
