# Generated by Django 5.1 on 2025-01-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awa", "0005_alter_sitelink_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitelink",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
