# Generated by Django 5.0.3 on 2024-03-05 20:02

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("awa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "auditedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="awa.auditedmodel",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            bases=("awa.auditedmodel",),
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "auditedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="awa.auditedmodel",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", django_quill.fields.QuillField()),
            ],
            bases=("awa.auditedmodel",),
        ),
    ]
