# Generated by Django 5.1 on 2023-10-09 17:08

import django.db.models.deletion
import django.db.models.manager
import django_currentuser.db.models.fields
import django_currentuser.middleware
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="blog_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "blogobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog_v1.blogobject",
                    ),
                ),
                (
                    "post_type",
                    models.IntegerField(choices=[(0, "Post"), (1, "Page")], default=0),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("subtitle", models.CharField(blank=True, max_length=80)),
                ("slug", models.SlugField()),
                ("draft", models.BooleanField(default=True)),
                ("search_text", models.TextField(blank=True)),
                ("tags", models.ManyToManyField(to="blog_v1.tag")),
            ],
            bases=("blog_v1.blogobject",),
            managers=[
                ("posts", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "blogobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog_v1.blogobject",
                    ),
                ),
                ("content", django_quill.fields.QuillField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="blog_v1.blogobject",
                    ),
                ),
            ],
            bases=("blog_v1.blogobject",),
        ),
        migrations.CreateModel(
            name="PostContent",
            fields=[
                (
                    "blogobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog_v1.blogobject",
                    ),
                ),
                ("content", django_quill.fields.QuillField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contents",
                        to="blog_v1.post",
                    ),
                ),
            ],
            bases=("blog_v1.blogobject",),
        ),
    ]
