# Generated by Django 5.1 on 2023-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.IntegerField(choices=[(0, "Post"), (1, "Page")], default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="priority",
            field=models.IntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0
            ),
        ),
    ]
