# Generated by Django 5.0a1 on 2023-09-25 21:34

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcontent",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
