# Generated by Django 5.0a1 on 2023-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="first_post", max_length=20),
            preserve_default=False,
        ),
    ]
