# Generated by Django 5.1 on 2023-10-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0002_delete_postcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-priority", "-modified")},
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Post"), (1, "Page")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                    (18, 18),
                    (19, 19),
                    (20, 20),
                    (21, 21),
                    (22, 22),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog_v1.tag"),
        ),
        migrations.CreateModel(
            name="Blip",
            fields=[
                (
                    "blogobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog_v1.blogobject",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "unique_together": {("url", "text", "image")},
            },
            bases=("blog_v1.blogobject",),
        ),
    ]
