# Generated by Django 5.0a1 on 2023-09-25 21:35

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0002_alter_postcontent_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
