# Generated by Django 5.1 on 2023-10-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0003_alter_post_options_alter_post_post_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                    (12, 12),
                    (13, 13),
                    (14, 14),
                    (15, 15),
                    (16, 16),
                    (17, 17),
                    (18, 18),
                    (19, 19),
                    (20, 20),
                    (21, 21),
                    (22, 22),
                    (23, 23),
                ],
                default=0,
            ),
        ),
    ]
