# Generated by Django 5.1 on 2023-10-23 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0004_alter_post_priority"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name="postcontent",
            order_with_respect_to="parent",
        ),
    ]
