# Generated by Django 5.1 on 2023-10-28 12:38

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0005_alter_postcontent_order_with_respect_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogobject",
            options={"permissions": [("view_private", "View non-public posts")]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"permissions": [("view_private_tag", "Access to this tag")]},
        ),
        migrations.RemoveField(
            model_name="blogobject",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.AddField(
            model_name="blogobject",
            name="modified_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="blogs_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blogobject",
            name="secret",
            field=models.PositiveSmallIntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0
            ),
        ),
        migrations.AddField(
            model_name="blogobject",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog_v1.tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="blogobject",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
