# Generated by Django 5.0a1 on 2023-10-05 19:24

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0005_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("posts", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
