# Generated by Django 5.0a1 on 2023-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0006_alter_post_managers_post_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="search_text",
            field=models.TextField(blank=True),
        ),
    ]
