# Generated by Django 5.1 on 2023-10-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0006_alter_blogobject_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="public",
        ),
        migrations.AddField(
            model_name="tag",
            name="secret",
            field=models.PositiveSmallIntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0
            ),
        ),
    ]
