# Generated by Django 5.1 on 2023-10-30 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0007_remove_tag_public_tag_secret"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogobject",
            options={"permissions": []},
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="secret",
            new_name="security_level",
        ),
        migrations.RemoveField(
            model_name="blogobject",
            name="secret",
        ),
    ]
