# Generated by Django 5.1 on 2023-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0008_alter_blogobject_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Post"),
                    (1, "Page"),
                    (2, "Page (Top)"),
                    (3, "Page (End)"),
                ],
                default=0,
            ),
        ),
    ]
