# Generated by Django 5.1 on 2023-12-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_v1", "0009_alter_post_post_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogobject",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.AlterField(
            model_name="tag",
            name="security_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Public"),
                    (1, "Users"),
                    (2, "Friends"),
                    (3, "Classified"),
                    (4, "Secret"),
                ],
                default=0,
            ),
        ),
    ]
