# Generated by Django 5.0.7 on 2024-08-06 15:02

import apps.huri.models
import awa.models
import colorfield.fields
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "label",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "label_bg",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThemeIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        height_field="icon_height",
                        null=True,
                        upload_to=functools.partial(
                            awa.models.image_upload_to, *(), **{"role": "icons"}
                        ),
                        width_field="icon_width",
                    ),
                ),
                (
                    "icon_height",
                    models.PositiveSmallIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "icon_width",
                    models.PositiveSmallIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "icon_type",
                    models.FilePathField(
                        match=".*\\.(png)$",
                        max_length=20,
                        path=apps.huri.models.ICON_TYPE_PATH,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icons",
                        to="huri.theme",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="themeicon",
            constraint=models.UniqueConstraint(
                fields=("theme", "icon_type"), name="unique_icon_type_per_theme"
            ),
        ),
    ]
