# Generated by Django 5.0.7 on 2024-08-03 13:30

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        height_field="icon_height",
                        null=True,
                        upload_to="icons/",
                        width_field="icon_width",
                    ),
                ),
                (
                    "icon_height",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("icon_width", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "label_color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "label_bg_color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "add_icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="huri.icon",
                    ),
                ),
                (
                    "change_icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="huri.icon",
                    ),
                ),
                (
                    "delete_icon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="huri.icon",
                    ),
                ),
            ],
        ),
    ]
