# Generated by Django 5.1 on 2024-08-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huri", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themeicon",
            name="icon_type",
            field=models.FilePathField(
                match=".*\\.(png)$",
                max_length=20,
                path="/home/matt/hack/awa/apps/huri/resources/themes/default",
                recursive=True,
            ),
        ),
    ]
