# Generated by Django 5.0.7 on 2024-08-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huri", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theme",
            old_name="add_icon",
            new_name="add",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="change_icon",
            new_name="change",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="delete_icon",
            new_name="delete",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="label_color",
            new_name="label",
        ),
        migrations.RenameField(
            model_name="theme",
            old_name="label_bg_color",
            new_name="label_bg",
        ),
    ]
