# Generated by Django 5.0.7 on 2024-08-03 14:05

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huri", "0002_rename_add_icon_theme_add_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="add",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="huri.icon",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="change",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="huri.icon",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="delete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="huri.icon",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="label_bg",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
