# Generated by Django 5.0.7 on 2024-08-04 16:32

import awa.models
import django.db.models.deletion
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huri", "0003_alter_theme_add_alter_theme_change_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="add",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="change",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="delete",
        ),
        migrations.AlterField(
            model_name="icon",
            name="icon",
            field=models.ImageField(
                blank=True,
                height_field="icon_height",
                null=True,
                upload_to=functools.partial(
                    awa.models.image_directory, *(), **{"role": "icons"}
                ),
                width_field="icon_width",
            ),
        ),
        migrations.CreateModel(
            name="ThemeIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        height_field="icon_height",
                        null=True,
                        upload_to=functools.partial(
                            awa.models.image_directory, *(), **{"role": "icons"}
                        ),
                        width_field="icon_width",
                    ),
                ),
                (
                    "icon_height",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("icon_width", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "icon_type",
                    models.PositiveSmallIntegerField(choices=[(0, "logo")], default=0),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icons",
                        to="huri.theme",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="themeicon",
            constraint=models.UniqueConstraint(
                fields=("theme", "icon_type"), name="unique_icon_type_per_theme"
            ),
        ),
    ]
